platform :ios, '13.0'

use_frameworks! :linkage => :static

target 'DanceUIRuntime_Example' do
  	pod 'DanceUIRuntime', :path => '../', :testspecs => ['UnitTests']
  	pod 'swift', :path => '../../DanceUIDependencies/swift'
  	pod 'boost', :path => '../../DanceUIDependencies/boost'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "13.0"
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
      config.build_settings["BUILD_LIBRARY_FOR_DISTRIBUTION"] = "NO"
    end
  end
end
